apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app-pull
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: tanzu-java-web-app
spec:
  source:
    git:
      url: https://github.com/J-kolaric/tanzu-java-web-app.git
      ref:
        branch: main
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
###### Specific scan policies for workload ####
  - name: scanning_source_policy
    value: scan-policy
  - name: scanning_image_policy
    value: scan-policy
###### END Specific scan policies for workload ####
###### Specific GITOPS to push code into git ####
  - name: gitops_server_address
    value: https://github.com/
  - name: gitops_repository_owner
    value: J-kolaric
  - name: gitops_repository_name
    value: tap-deliverables
  - name: gitops_ssh_secret
    value: git-ssh
  - name: gitops_user_email
    value: tanzu-java-web-app-dev@vmware.com
  - name: gitops_commit_message
    value: "Commit message from tanzu-java-web-app-dev workload"
###### END Specific GITOPS to push code into git ####
###### Specific GITOPS pull request ####
  - name: gitops_server_kind
    value: github
  - name: gitops_commit_branch
    value: dev
  - name: gitops_pull_request_title
    value: "tanzu-java-web-app ready for review from dev workload"
  - name: gitops_pull_request_body
    value: "generated by tanzu-java-web-app supply chain from dev workload"
###### END Specific GITOPS pull request ####
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
